import { AIAnalysis, RiskStatus } from "@prisma/client";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Bot, CheckCircle2, AlertTriangle, AlertCircle } from "lucide-react";
import { cn } from "@/lib/utils";

interface InsightCardProps {
  analysis: AIAnalysis;
}

export function InsightCard({ analysis }: InsightCardProps) {
  const isRisk = analysis.riskFlag === "RISK";

  return (
    <Card className="w-full border-l-4 border-l-[#2D6A4F] shadow-sm">
      <CardHeader className="pb-4">
        <CardTitle className="flex items-center gap-2 text-xl font-semibold text-[#2D6A4F]">
          <Bot className="h-6 w-6" />
          AI Session Analysis
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* A. SESSION SUMMARY */}
        <div className="space-y-2">
          <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Session Summary</h3>
          <p className="text-sm leading-relaxed text-foreground">{analysis.summary}</p>
        </div>

        <Separator />

        {/* B. QUALITY SCORES */}
        <div className="space-y-6">
            <h3 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">Quality Scores</h3>
            
            <ScoreRow 
                label="Content Coverage"
                score={analysis.contentCoverageScore}
                justification={analysis.contentCoverageJustification}
                maxScore={3}
            />
            
            <Separator className="my-2" />
            
            <ScoreRow 
                label="Facilitation Quality"
                score={analysis.facilitationScore}
                justification={analysis.facilitationJustification}
                maxScore={3}
            />

            <Separator className="my-2" />

            <ScoreRow 
                label="Protocol Safety"
                score={analysis.protocolSafetyScore}
                justification={analysis.protocolSafetyJustification}
                maxScore={3}
            />
        </div>

        <Separator />

        {/* C. RISK FLAG */}
        <div className="pt-2">
            {isRisk ? (
                <Alert variant="destructive" className="border-red-600 bg-red-50 text-red-900">
                    <AlertTriangle className="h-5 w-5 text-red-600" />
                    <AlertTitle className="mb-2 text-lg font-bold text-red-700">Protocol Risk Detected</AlertTitle>
                    <AlertDescription className="space-y-3">
                        <p className="font-semibold">This session has been flagged for immediate supervisor review.</p>
                        {analysis.riskQuote && (
                             <blockquote className="border-l-4 border-red-500 bg-red-100 p-3 italic text-red-900 rounded-r">
                                "{analysis.riskQuote}"
                            </blockquote>
                        )}
                    </AlertDescription>
                </Alert>
            ) : (
                <Alert className="border-green-600 bg-green-50 text-green-900">
                    <CheckCircle2 className="h-5 w-5 text-green-600" />
                    <AlertTitle className="text-lg font-semibold text-green-800">No Risk Signals Detected</AlertTitle>
                    <AlertDescription>
                        The session followed safety protocols with no indicators of self-harm or crisis.
                    </AlertDescription>
                </Alert>
            )}
        </div>

        {/* D. DISCLAIMER */}
        <div className="flex items-center justify-center gap-2 pt-4 text-xs text-muted-foreground">
            <Bot className="h-3 w-3" />
            <span>Generated by AI · Pending supervisor review</span>
        </div>
      </CardContent>
    </Card>
  );
}

function ScoreRow({ label, score, justification, maxScore }: { label: string, score: number, justification: string, maxScore: number }) {
    // Generate circles
    const circles = [];
    for (let i = 1; i <= maxScore; i++) {
        circles.push(
            <div 
                key={i}
                className={cn(
                    "h-3 w-3 rounded-full border border-primary transition-colors",
                    i <= score ? "bg-primary border-primary" : "bg-transparent border-muted-foreground/30"
                )}
            />
        );
    }

    const getScoreLabel = (val: number, type: 'content' | 'facilitation' | 'safety') => {
        const ratings = {
            content: { 1: "Missed", 2: "Partial", 3: "Complete" },
            facilitation: { 1: "Poor", 2: "Adequate", 3: "Excellent" },
            safety: { 1: "Violation", 2: "Minor Drift", 3: "Adherent" }
        };
        // @ts-ignore - indexes are safe
        const label = ratings[type][val] || "Unknown";
        return `${val} / ${maxScore} — ${label}`;
    };

    return (
        <div className="space-y-1">
            <div className="flex items-center justify-between">
                <span className="font-semibold text-sm">{label}</span>
                <div className="flex items-center gap-3">
                    <div className="flex gap-1">{circles}</div>
                    <span className="text-sm font-medium">{getScoreLabel(score, labelToType(label))}</span>
                </div>
            </div>
            <p className="text-xs text-muted-foreground leading-snug">
                {justification}
            </p>
        </div>
    );
}

function labelToType(label: string): 'content' | 'facilitation' | 'safety' {
    if (label.includes("Content")) return 'content';
    if (label.includes("Facilitation")) return 'facilitation';
    return 'safety';
}
